using SymPy
@syms x, θ

v1(x) = log(2 + sin(x))
v2(x) = exp(tan(x))
v3(x) = log(sec(x)+tan(x))
v4(x) = -log(csc(x) + cot(x))
v5(x) = asin(2x^2)
v6(x) = acos(exp(x))
v7(x) = (x^3)*(atan(exp(x)))
v8(x) = exp(x)*asin(x^2)
v9(x) = (atan(x))^3
v10(x) = tan(acos(x))
v11(x) = asec(x^3)
v12(x) = (asec(x))^3
v13(x) = (1 + asin(x))^3
v14(x) = asin(1/(x^2 + 4))
v15(x) = atan(log(x^2))
v16(x) = x*(asec(x^2 + 1))

V1 = diff((v1(x)), (x))
V2 = diff((v2(x)), (x))
V3 = diff((v3(x)), (x))
V4 = diff((v4(x)), (x))
V5 = diff((v5(x)), (x))
V6 = diff((v6(x)), (x))
V7 = diff((v7(x)), (x))
V8 = diff((v8(x)), (x))
V9 = diff((v9(x)), (x))
V10 = diff((v10(x)), (x))
V11 = diff((v11(x)), (x))
V12 = diff((v12(x)), (x))
V13 = diff((v13(x)), (x))
V14 = diff((v14(x)), (x))
V15 = diff((v15(x)), (x))
V16 = diff((v16(x)), (x))


println("Computing dy/dx")
println("a.  ", V1)
println("b.  ", V2)
println("c.  ", V3)
println("d.  ", V4)
println("e.  ", V5)
println("f.  ", V6)
println("g.  ", V7)
println("h.  ", V8)
println("i.  ", V9)
println("j.  ", V10)
println("k.  ", V11)
println("l.  ", V12)
println("m.  ", V13)
println("n.  ", V14)
println("o.  ", V15)
println("p.  ", V16)